P8105_hw1_qh2283
================
2023-09-20

``` r
library(moderndive)
library(ggplot2)
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ lubridate 1.9.2     ✔ tibble    3.2.1
    ## ✔ purrr     1.0.2     ✔ tidyr     1.3.0
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
#import the data 
data("early_january_weather")
early_january_weather
```

    ## # A tibble: 358 × 15
    ##    origin  year month   day  hour  temp  dewp humid wind_dir wind_speed
    ##    <chr>  <int> <int> <int> <int> <dbl> <dbl> <dbl>    <dbl>      <dbl>
    ##  1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4 
    ##  2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06
    ##  3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5 
    ##  4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7 
    ##  5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7 
    ##  6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5 
    ##  7 EWR     2013     1     1     7  39.0  28.0  64.4      240      15.0 
    ##  8 EWR     2013     1     1     8  39.9  28.0  62.2      250      10.4 
    ##  9 EWR     2013     1     1     9  39.9  28.0  62.2      260      15.0 
    ## 10 EWR     2013     1     1    10  41    28.0  59.6      260      13.8 
    ## # ℹ 348 more rows
    ## # ℹ 5 more variables: wind_gust <dbl>, precip <dbl>, pressure <dbl>,
    ## #   visib <dbl>, time_hour <dttm>

``` r
str(early_january_weather)
```

    ## tibble [358 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ origin    : chr [1:358] "EWR" "EWR" "EWR" "EWR" ...
    ##  $ year      : int [1:358] 2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
    ##  $ month     : int [1:358] 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ day       : int [1:358] 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ hour      : int [1:358] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ temp      : num [1:358] 39 39 39 39.9 39 ...
    ##  $ dewp      : num [1:358] 26.1 27 28 28 28 ...
    ##  $ humid     : num [1:358] 59.4 61.6 64.4 62.2 64.4 ...
    ##  $ wind_dir  : num [1:358] 270 250 240 250 260 240 240 250 260 260 ...
    ##  $ wind_speed: num [1:358] 10.36 8.06 11.51 12.66 12.66 ...
    ##  $ wind_gust : num [1:358] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ precip    : num [1:358] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ pressure  : num [1:358] 1012 1012 1012 1012 1012 ...
    ##  $ visib     : num [1:358] 10 10 10 10 10 10 10 10 10 10 ...
    ##  $ time_hour : POSIXct[1:358], format: "2013-01-01 01:00:00" "2013-01-01 02:00:00" ...

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
mean(early_january_weather$temp)
```

    ## [1] 39.58212

``` r
#use ggplot to create the scatter point plot for the data
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + geom_point()
```

![](P8105_hw1_qh2283_files/figure-gfm/unnamed-chunk-1-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", height = 4, width = 6)
```

Discription: The dataset contain 358 rows, 15 columns, and with the mean
temperature of 39.58. Within these 15 variables there is “temp”, which
represents the temperature (in degrees Fahrenheit) observed at that
hour. There is “humid”, which represents the humidity level observed at
that hour. there is “time_hour”, which represents the specific hour of
observation. There is “Wind_speed”, which represents the wind speed
observed at that hour.

``` r
library(tidyverse)
#set a normal distribution and pick number randomly from the normal distribution
a = rnorm(10)
#create a dataframe 
df <- data.frame(
  a,
  logical_vector = a > 0,
  char_vector    = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  factor_vector  = factor(rep(1:3, length.out = 10))
)
#print the dataframe
print(df)
```

    ##             a logical_vector char_vector factor_vector
    ## 1  -1.1419552          FALSE           a             1
    ## 2  -0.3037936          FALSE           b             2
    ## 3  -1.0469884          FALSE           c             3
    ## 4  -1.8254345          FALSE           d             1
    ## 5  -0.1588050          FALSE           e             2
    ## 6   1.2100423           TRUE           f             3
    ## 7   1.4638484           TRUE           g             1
    ## 8   1.8145163           TRUE           h             2
    ## 9  -0.2376794          FALSE           i             3
    ## 10  1.3913486           TRUE           j             1

``` r
#take the mean of a variable in the dataframe with "pull" function
mean_numeric <- mean(pull(df, a))
mean_numeric
```

    ## [1] 0.11651

``` r
mean_logical <- mean(pull(df, logical_vector))
mean_logical
```

    ## [1] 0.4

``` r
#Convert to Numeric
x=as.numeric(mean_numeric)
y=as.numeric(mean_logical)
#print the numeric 
x
```

    ## [1] 0.11651

``` r
y
```

    ## [1] 0.4
